variable "location" {
  description = "Azure region where all resources will be deployed."
  type        = string
}

variable "rg_name" {
  description = "Name of the Azure Resource Group where resources will be created."
  type        = string
}

variable "tags" {
  description = "Key value map of tags to assign to all supported Azure resources."
  type        = map(string)
  default     = {}
}

variable "aci_name" {
  description = "Name of the Azure Container Instance."
  type        = string
}

variable "ip_address_ty" {
  description = "Specifies whether the container group will have a Public or Private IP address."
  type        = string
  default     = "Public"
}

variable "dns_name_label" {
  description = "DNS name label for the public IP address of the container group. Must be unique within the Azure region."
  type        = string
}

variable "os_ty" {
  description = "Operating system typ for the container instance. Valid values are Linux or Windows."
  type        = string
  default     = "Linux"
}

variable "container_name" {
  description = "Name of the container within the container group."
  type        = string
}

variable "container_image" {
  description = "Container image to deploy, including registry and tag if applicable."
  type        = string
}

variable "container_config" {
  description = "CPU and memory resource configuration for the container."
  type = object({
    cpu    = number
    memory = number
  })
  default = {
    cpu    = 1
    memory = 1
  }
}

variable "ports" {
  description = "List of ports to expose from the container along with their protocol."
  type = list(object({
    port     = number
    protocol = string
  }))
  default = [
    {
      port     = 6379
      protocol = "TCP"
    }
  ]
}

variable "environment_variables" {
  description = "List of environment variables to inject into the container."
  type = list(object({
    name  = string
    value = string
  }))
  default = []
}

variable "password_config" {
  description = "Configuration for autogenerated password including length and special character rules."
  type = object({
    length           = number
    special          = bool
    override_special = string
  })
  default = {
    length           = 16
    special          = true
    override_special = "!#$%&*()-_=+[]{}<>:?"
  }
}

# Key Vault
variable "key_vault_id" {
  description = "Resource ID of the Azure Key Vault where secrets will be stored."
  type        = string
}

variable "redis_hostname_secret_name" {
  description = "Name of the Key Vault secret that will store the Redis hostname."
  type        = string
}

variable "redis_password_secret_name" {
  description = "Name of the Key Vault secret that will store the Redis password."
  type        = string
}
